### ISSUE TITLE
Error 500 when trying to use a refdata attribute as a filter in the Export Builder

### ISSUE THREAD

**Issue by Schwierig** [akeneo-labs/CustomEntityBundle#169]
When using a custom entity as an Akeneo attribute it does not return the "entity_class" property that is set in "custom_entities.yml" by default.

Do I need to define it elsewhere, because I can't seem to find any mention of that in the docs.

**Comment by mmetayer** [comment]
Hello @Schwierig, in order to use custom entities for reference data simple or multi select attributes, you have to configure the `pim_reference_data` config key in `app/config/config.yml`, see https://docs.akeneo.com/2.2/manipulate_pim_data/catalog_structure/creating_a_reference_data.html#configuring-the-reference-data.
An example of configuration is also provided [here](https://github.com/akeneo-labs/CustomEntityBundle/tree/master/docs/examples/bin/config/config-reference-data.yml)

**Comment by Schwierig** [comment]
Actually I already did that. I can use it in the product with any problems. My problem is that I cannot use the reference data as a filter in the export. When researching this I stumbled upon the "entity_class" which isn't being returned by the class.

**Comment by mmetayer** [comment]
Hi again @Schwierig, I updated the issue's title, there was indeed a bug related to the export builder, which should be fixed by #176
