### ISSUE TITLE
Cannot install for Akeneo 3

### ISSUE THREAD

**Issue by karelVanGeerdeghom** [akeneo-labs/CustomEntityBundle#200]
I've added the following to my composer.json
```"minimum-stability": "dev"```
but when I try to run
```composer require "akeneo-labs/custom-entity-bundle":"3.1.x-dev"```
I get
```
Problem 1
    - The requested package akeneo-labs/custom-entity-bundle 3.1.x-dev exists as akeneo-labs/custom-entity-bundle[1.0.0, 1.10.x-dev, 1.5.x-dev, 1.6.x-dev, 1.7.x-dev, 1.9.x-dev, 2.0.x-dev, 3.0.x-dev, dev-fix-import-with-translations, dev-github-137, dev-master, dev-mmetayer-patch-1, v1.1.0, v1.1.1, v1.10.0, v1.10.1, v1.10.2, v1.10.3, v1.10.4, v1.10.5, v1.10.6, v1.10.7, v1.10.8, v1.10.9, v1.2.0, v1.3.0, v1.3.0-RC1, v1.3.0-alpha1, v1.4.0, v1.5.0-RC1, v1.6-RC1, v1.6.0, v1.6.0-RC2, v1.6.0-alpha1, v1.7.0, v1.8.0, v1.9.0, v1.9.0-RC1, v1.9.1, v2.0.0-beta, v2.0.2-beta, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.2.0, v2.2.1, v2.2.2, v2.3.0, v2.4.0, v3.0.0] but these are rejected by your constraint.
```

**Comment by jmleroux** [comment]
Hello @karelVanGeerdeghom ,

The README might be clearer, because the one you read is for using this bundle with master branch of the PIM. If you look at the [tag README](https://github.com/akeneo-labs/CustomEntityBundle/tree/v3.0.0), the requirement is more correct.
I'll fix the master README to repuire the 3.0.0 version to avoid this kind of mistake.

Regards,
JM

**Comment by jmleroux** [comment]
Fixed. Please close this issue if the fix is ok for you.

**Comment by karelVanGeerdeghom** [comment]
Yes, that helped, thx!
